services:
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: aynia-db
      ADMINER_DESIGN: nette
    depends_on:
      - aynia-db
